### ISSUE TITLE
CRD on Namespace

### ISSUE THREAD

**Issue by caiohasouza** [evalsocket/oldmonk#38]
It's possible create a [CRD](https://github.com/evalsocket/oldmonk/blob/master/deploy/crds/oldmonk.evalsocket.in_queueautoscalers_crd.yaml)  on namespace scope? Currently the CRD is created a cluster scoped,

**Comment by evalsocket** [comment]
@caiohasouza . We can create CRD in two types i.e. `Namespaced` and  `cluster`. Read [this](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)

**Comment by evalsocket** [comment]
And It's kubernetes behavior so we can close this

**Comment by caiohasouza** [comment]
@evalsocket right, i can see that CRD is Namespaced scope, but when i will create i have this error:

> customresourcedefinitions.apiextensions.k8s.io "queueautoscalers.oldmonk.evalsocket.in" is forbidden: User "system:serviceaccount:USER:tiller" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" **at the cluster scope**

The K8S user that will create the CRD needs cluster scope permission to create a resource?

**Comment by evalsocket** [comment]
@caiohasouza  Both options are working for me

**Comment by caiohasouza** [comment]
Are you creating with command:

> kubectl apply -f https://raw.githubusercontent.com/evalsocket/oldmonk/master/deploy/crds/oldmonk.evalsocket.in_queueautoscalers_crd.yaml

And use k8s user without cluster rbac permission?

**Comment by evalsocket** [comment]
I am using `make install`. But internally it is also using same command. Remove your existing crd deployment and then redeployed it

**Comment by caiohasouza** [comment]
@evalsocket we talked on Slack and you will make some internal tests, i'm waiting.

**Comment by evalsocket** [comment]
@caiohasouza Got the issue. Interested to understand why are you deploying it without permission?

**Comment by caiohasouza** [comment]
@evalsocket cool, n my environment i have 1 "deployment user" in each namespace, this user have a Role with permissions to create/update/delete only resources in your namespace, it's to prevent user create resources in other namespace, just to security reasons, do you understand?

**Comment by evalsocket** [comment]
We can close this
