### ISSUE TITLE
Helm Chart Repository

### ISSUE THREAD

**Issue by caiohasouza** [evalsocket/oldmonk#40]
We need create a public helm chart repository to be possible users add oldmonk repo and deploy the release, it's possible use Github pages, some refs:

> https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417
> https://pages.github.com/

How can we proceed?

**Comment by evalsocket** [comment]
@caiohasouza  you can start working on this

**Comment by caiohasouza** [comment]
@evalsocket Ok, we need a some CI/CD solution to:

- Create a helm chart package;
- Test helm sintax;
- Create a hem repo index file;
- Pull code to Github;

Are you using some solution?

**Comment by evalsocket** [comment]
Releated #37

**Comment by evalsocket** [comment]
Let's do it with #37 and close this one
