### ISSUE TITLE
Create Documentation 

### ISSUE THREAD

**Issue by evalsocket** [evalsocket/oldmonk#8]
Write documentation of API type for auto-generated  documentation

**Comment by evalsocket** [comment]
Releated #39

**Comment by evalsocket** [comment]
@caiohasouza What about a blog ? That will explain the entire process

**Comment by caiohasouza** [comment]
@evalsocket i thought in a simple text file on docs/, the process is very simple.

**Comment by evalsocket** [comment]
Apart from that blog will cover all the options

**Comment by caiohasouza** [comment]
right, and how can i help?
